name: "Setup Node.js and Dependencies"
description: "Setup Node.js from .nvmrc and install dependencies with caching"

runs:
  using: "composite"
  steps:
    - name: Read Node.js version
      id: nvmrc
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm ci
